#!/bin/bash -l
#SBATCH --job-name=MD_RNA
#SBATCH --gres=gpu
#SBATCH -p biomed_a30_gpu 
#SBATCH --mem=8G
#SBATCH --time=48:00:00
#SBATCH --ntasks=1
#SBATCH --no-requeue


echo $hostname

nvidia-debugdump -l

nvidia-smi

cd ${SLURM_SUBMIT_DIR}

#initial minimisation, constrained peptide
/users/k2262470/amber22/bin/pmemd.cuda -O -i initmin.in -o initmin.out -c coords.inpcrd -p coords.prmtop -r initmin.rst -ref coords.inpcrd
#initial minimisation no constraints
/users/k2262470/amber22/bin/pmemd.cuda -O -i fullmin.in -o fullmin.out -c initmin.rst -p coords.prmtop -r fullmin.rst -ref initmin.rst

#solvation equilibrium (heating and removing constraints)
/users/k2262470/amber22/bin/pmemd.cuda -O -i solveq1.in -o solveq1.out -c fullmin.rst -p coords.prmtop -r solvated1_q1.rst -ref fullmin.rst -x solvated1_q1.mdcrd
/users/k2262470/amber22/bin/pmemd.cuda -O -i solveq2.in -o solveq2.out -c solvated1_q1.rst -p coords.prmtop -r solvated2_q1.rst -ref solvated1_q1.rst -x solvated2_q1.mdcrd
/users/k2262470/amber22/bin/pmemd.cuda -O -i solveq3.in -o solveq3.out -c solvated2_q1.rst -p coords.prmtop -r solvated3_q1.rst -ref solvated2_q1.rst -x solvated3_q1.mdcrd
/users/k2262470/amber22/bin/pmemd.cuda -O -i solveq4.in -o solveq4.out -c solvated3_q1.rst -p coords.prmtop -r solvated4_q1.rst -ref solvated3_q1.rst -x solvated4_q1.mdcrd
/users/k2262470/amber22/bin/pmemd.cuda -O -i solveq5.in -o solveq5.out -c solvated4_q1.rst -p coords.prmtop -r solvated5_q1.rst -ref solvated4_q1.rst -x solvated5_q1.mdcrd

#NPT relaxation with and without restraints
/users/k2262470/amber22/bin/pmemd.cuda -O -i npt_restr.in -o npt_restr.out -c solvated5_q1.rst -p coords.prmtop -r npt_initial.rst -ref solvated5_q1.rst -x npt_init.mdcrd
/users/k2262470/amber22/bin/pmemd.cuda -O -i npt.in -o npt.out -c npt_initial.rst -p coords.prmtop -r npt_final.rst -x npt.mdcrd

#production run
/users/k2262470/amber22/bin/pmemd.cuda -O -i nvt.in -o nvt1.out -c npt_final.rst -p coords.prmtop -r nvt1.rst -x nvt1.mdcrd
/users/k2262470/amber22/bin/pmemd.cuda -O -i nvt.in -o nvt2.out -c npt_final.rst -p coords.prmtop -r nvt2.rst -x nvt2.mdcrd
/users/k2262470/amber22/bin/pmemd.cuda -O -i nvt.in -o nvt3.out -c npt_final.rst -p coords.prmtop -r nvt3.rst -x nvt3.mdcrd
